DROP DATABASE IF EXISTS MERCADO;
CREATE DATABASE MERCADO;
USE MERCADO;

DROP USER IF EXISTS 'mercado'@'localhost';
CREATE USER 'mercado'@'localhost' IDENTIFIED BY '123456';
GRANT SELECT, UPDATE, DELETE, INSERT ON MERCADO.* TO 'mercado'@'localhost';

CREATE TABLE PRODUTO (
	PROD_ID_PRODUTO 	INT 			NOT NULL 	AUTO_INCREMENT,
	PROD_TX_DESCRICAO 	VARCHAR(50)		NOT NULL,
	PROD_VL_PRECO 		DECIMAL(5,2)	NOT NULL,
	PRIMARY KEY (PROD_ID_PRODUTO)
);